name: hello world
no: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!" 
      - name: my-step
        run: echo "Attending workshop" 
       - name: my-step
         run: echo "Alloting work
